"""Generate deterministic, scene-aligned Cixa narration with Kokoro-82M."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import soundfile as sf

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "narration.json"
OUT = ROOT / "public" / "voiceover"
GENERATED = ROOT / "src" / "generated" / "voiceover.ts"
SAMPLE_RATE = 24_000
VOICE = os.environ.get("KOKORO_VOICE", "af_heart")
SEED = 7
LEAD_SECONDS = 0.45
TAIL_SECONDS = 0.75


def synth(pipeline, text: str) -> tuple[np.ndarray, list[dict[str, float | str]]]:
    import torch

    torch.manual_seed(SEED)
    audio_parts: list[np.ndarray] = []
    words: list[dict[str, float | str]] = []
    offset = LEAD_SECONDS
    for result in pipeline(text, voice=VOICE, speed=0.96):
        audio = np.asarray(result.audio, dtype=np.float32)
        for token in result.tokens or []:
            if token.start_ts is None or token.end_ts is None:
                continue
            if not any(character.isalnum() for character in token.text):
                continue
            displayed = {"jee": "Cixa", "jee-khah": "Cixa", "jeekha": "Cixa", "khah": ""}.get(
                token.text.lower(), token.text
            )
            if not displayed:
                continue
            words.append(
                {
                    "text": displayed,
                    "start": round(offset + token.start_ts, 3),
                    "end": round(offset + token.end_ts, 3),
                }
            )
        audio_parts.append(audio)
        offset += len(audio) / SAMPLE_RATE
    if not audio_parts:
        raise RuntimeError(f"Kokoro returned no audio for {text[:50]!r}")
    lead = np.zeros(round(LEAD_SECONDS * SAMPLE_RATE), dtype=np.float32)
    tail = np.zeros(round(TAIL_SECONDS * SAMPLE_RATE), dtype=np.float32)
    return np.concatenate([lead, *audio_parts, tail]), words


def make_bed(duration: float) -> None:
    output = OUT / "ambient.m4a"
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"sine=frequency=110:sample_rate=48000:duration={duration}",
            "-f",
            "lavfi",
            "-i",
            f"sine=frequency=164.81:sample_rate=48000:duration={duration}",
            "-f",
            "lavfi",
            "-i",
            f"sine=frequency=220:sample_rate=48000:duration={duration}",
            "-filter_complex",
            "[0:a]volume=0.018[a0];[1:a]volume=0.010[a1];[2:a]volume=0.006[a2];"
            "[a0][a1][a2]amix=inputs=3,lowpass=f=850,afade=t=in:st=0:d=2,"
            f"afade=t=out:st={max(0.0, duration - 3):.3f}:d=3[out]",
            "-map",
            "[out]",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            str(output),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def main() -> None:
    try:
        from kokoro import KPipeline
    except ImportError:
        configured = os.environ.get("KOKORO_PYTHON")
        if configured and Path(configured).resolve() != Path(sys.executable).resolve():
            os.execv(configured, [configured, *sys.argv])
        raise SystemExit(
            "Kokoro is not installed for this Python. Set KOKORO_PYTHON to its interpreter."
        )

    OUT.mkdir(parents=True, exist_ok=True)
    for legacy_wav in OUT.glob("*.wav"):
        legacy_wav.unlink()
    scenes = json.loads(SCRIPT.read_text())
    pipeline = KPipeline(lang_code=VOICE[0])
    generated: list[dict] = []

    for scene in scenes:
        speech = scene["text"].replace("Cixa", "Jee-khah")
        audio, words = synth(pipeline, speech)
        wav_target = OUT / f"{scene['id']}.wav"
        target = OUT / f"{scene['id']}.m4a"
        sf.write(wav_target, audio, SAMPLE_RATE, subtype="PCM_16")
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(wav_target),
                "-c:a",
                "aac",
                "-b:a",
                "112k",
                str(target),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        wav_target.unlink()
        duration = len(audio) / SAMPLE_RATE
        generated.append(
            {
                "id": scene["id"],
                "audio": f"voiceover/{scene['id']}.m4a",
                "duration": round(duration, 3),
                "text": scene["text"],
                "words": words,
            }
        )
        print(f"{scene['id']:<12} {duration:5.1f}s")

    total = sum(scene["duration"] for scene in generated)
    make_bed(total + 1)
    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(
        "// Generated by scripts/generate_voiceover.py.\n"
        f"export const voiceover = {json.dumps(generated, indent=2)} as const;\n"
    )
    print(f"total        {total:5.1f}s")


if __name__ == "__main__":
    main()
